apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emissions-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: app.emissionsv2.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emissions-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: emissions-backend
                port:
                  number: 4000
