apiVersion: v1
kind: Service
metadata:
  name: emissions-backend
spec:
  selector:
    app: emissions-backend
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: emissions-frontend
spec:
  selector:
    app: emissions-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
